In [ ]:
import numpy as np
import pandas as pd
import nltk
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from tensorflow import keras
from tensorflow.keras.layers import Embedding,Dense,Masking,SimpleRNN,Bidirectional
from tensorflow.keras.models import Sequential
from tensorflow.keras.activations import sigmoid,softmax
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
docs = [
    "excellent service",
    "poor service",
    "very happy with the product",
    "very disappointed with the product",
    "delivery was fast",
    "delivery was late",
    "quality exceeded expectations",
    "quality was bad",
    "highly recommended",
    "not recommended",
    "good customer support",
    "terrible customer support",
    "easy to use application",
    "application keeps crashing",
    "fantastic experience",
    "worst experience ever",
    "worth buying",
    "waste of money",
    "best purchase ever",
    "not worth the money"
]

labels = [1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0]

In [ ]:
train_independent_data=docs[:17]
val_independent_data=docs[17:19]
test_independent_data=docs[19:]

In [ ]:
train_dependent_data=labels[:17]
val_dependent_data=labels[17:19]
test_dependent_data=labels[19:]

In [ ]:
dict_size=1000

In [ ]:
train_ind_val=[]
for i in train_independent_data:
   train_ind_val.append(one_hot(i,dict_size))
print(train_ind_val)

[[943, 761], [202, 761], [75, 69, 368, 219, 626], [75, 314, 368, 219, 626], [370, 643, 564], [370, 643, 261], [299, 638, 375], [299, 643, 186], [386, 778], [621, 778], [514, 356, 203], [88, 356, 203], [903, 123, 816, 762], [762, 174, 872], [382, 565], [624, 565, 321], [267, 876]]


In [ ]:
valid_ind_val=[]
for i in val_independent_data:
   valid_ind_val.append(one_hot(i,dict_size))
print(valid_ind_val)

[[790, 976, 270], [512, 486, 321]]


In [ ]:
train_inputs=pad_sequences(train_ind_val,maxlen=10,padding='post')
print(train_inputs)

[[943 761   0   0   0   0   0   0   0   0]
 [202 761   0   0   0   0   0   0   0   0]
 [ 75  69 368 219 626   0   0   0   0   0]
 [ 75 314 368 219 626   0   0   0   0   0]
 [370 643 564   0   0   0   0   0   0   0]
 [370 643 261   0   0   0   0   0   0   0]
 [299 638 375   0   0   0   0   0   0   0]
 [299 643 186   0   0   0   0   0   0   0]
 [386 778   0   0   0   0   0   0   0   0]
 [621 778   0   0   0   0   0   0   0   0]
 [514 356 203   0   0   0   0   0   0   0]
 [ 88 356 203   0   0   0   0   0   0   0]
 [903 123 816 762   0   0   0   0   0   0]
 [762 174 872   0   0   0   0   0   0   0]
 [382 565   0   0   0   0   0   0   0   0]
 [624 565 321   0   0   0   0   0   0   0]
 [267 876   0   0   0   0   0   0   0   0]]


In [ ]:
val_inputs=pad_sequences(valid_ind_val,maxlen=10,padding='post')
print(val_inputs)

[[790 976 270   0   0   0   0   0   0   0]
 [512 486 321   0   0   0   0   0   0   0]]


In [ ]:
train_labels=np.array(train_dependent_data).reshape(-1,1)
val_labels=np.array(val_dependent_data).reshape(-1,1)
train_labels

array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1]])

In [ ]:
train_labels.shape

(17, 1)

In [ ]:
val_labels.shape

(2, 1)

In [ ]:
model=Sequential()

In [ ]:
model.add(Embedding(input_dim=dict_size,output_dim=10,input_length=15))

model.add(Masking(mask_value=0.0))

model.add(Bidirectional(SimpleRNN(units=10,return_sequences=True,name='Hidden_layer1')))
model.add(Bidirectional(SimpleRNN(units=15,return_sequences=True,name='Hidden_layer2')))
model.add(Bidirectional(SimpleRNN(units=20,return_sequences=False,name='Hidden_layer3')))

model.add(Dense(units=1,activation=sigmoid,name='Output_layer'))

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ masking (Masking)               │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_2 (Bidirectional) │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Output_layer (Dense)            │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
print(train_inputs.shape)
print(val_inputs.shape)

(17, 10)
(2, 10)


In [ ]:
model.fit(train_inputs,train_labels,epochs=2,batch_size=1,validation_data=(val_inputs,val_labels))

Epoch 1/2
17/17 ━━━━━━━━━━━━━━━━━━━━ 12s 104ms/step - accuracy: 0.2941 - loss: 0.8711 - val_accuracy: 0.5000 - val_loss: 0.7511
Epoch 2/2
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5882 - loss: 0.6645 - val_accuracy: 0.0000e+00 - val_loss: 0.8063


In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (1, 10, 10)            │        10,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ masking (Masking)               │ (1, 10, 10)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (1, 10, 20)            │           420 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ (1, 10, 30)            │         1,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_2 (Bidirectional) │ (1, 40)                │         2,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Output_layer (Dense)            │ (1, 1)                 │            41 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 40,745 (159.16 KB)

 Trainable params: 13,581 (53.05 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 27,164 (106.11 KB)

Prediction

In [ ]:
check=['hard to understand topics']
f=one_hot(check[0],dict_size)

f1=pad_sequences([f],maxlen=10,padding='post')

res=model.predict(f1)
print(res)

1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
[[0.5588947]]


In [ ]:
if res[0][0]>0.5:
  print('Good')
else:
  print('bad')

bad
